#!/bin/bash

docker network create -d bridge fishubu-net

mkdir -p $1 2> /dev/null

bash ../helpers/spark-cluster-up.sh $1 $2 $3 $4 $5

touch /tmp/clusters.$2 # Se guarda el número de clústers que se van a usar

cd ../../dockers/kafka
docker-compose up --force-recreate -d
